// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(Link_t *pmail)
{
    printf("DEBUG ui_Screen1_screen_init\n");
    Que_Data_t data;
    char buf[100] = {0};
    recv_msg(pmail,&data);
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 98);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 0);
    lv_obj_set_y(ui_Button1, 180);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "监控");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_eyes, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -38);
    lv_obj_set_y(ui_Label1, -194);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "秦岭智能生态监测系统");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_text, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -239);
    lv_obj_set_y(ui_Label2, -100);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    sprintf(buf,"温度：%.2f",data.temp);
    lv_label_set_text(ui_Label2, buf);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_temp, LV_PART_MAIN | LV_STATE_DEFAULT);
    //printf("DEBUG tem : %s\n", buf);
    memset(buf, 0, sizeof(buf));

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -241);
    lv_obj_set_y(ui_Label3, -55);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    sprintf(buf,"湿度：%.2f",data.hum);
    lv_label_set_text(ui_Label3, buf);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_hum, LV_PART_MAIN | LV_STATE_DEFAULT);
    //printf("DEBUG hum : %s\n", buf);
    memset(buf, 0, sizeof(buf));

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -238);
    lv_obj_set_y(ui_Label4, -6);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    sprintf(buf,"光照强度：%.2f",data.light);
    lv_label_set_text(ui_Label4, buf);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_sun, LV_PART_MAIN | LV_STATE_DEFAULT);
    //printf("DEBUG light : %s\n", buf);
    memset(buf, 0, sizeof(buf));

    ui_Label5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -238);
    lv_obj_set_y(ui_Label5, 49);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    sprintf(buf,"烟雾浓度：%f",data.smoke);
    lv_label_set_text(ui_Label5, buf);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_smoke, LV_PART_MAIN | LV_STATE_DEFAULT);
    //printf("DEBUG smoke : %s\n", buf);
    memset(buf, 0, sizeof(buf));

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Button1 = NULL;
    ui_Label6 = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    ui_Label3 = NULL;
    ui_Label4 = NULL;
    ui_Label5 = NULL;

}
