// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"
#include "../..//include/list.h"
#include "../../include/queue.h"

void ui_Screen1_screen_init(void);

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_text);
LV_FONT_DECLARE(ui_font_temp);
LV_FONT_DECLARE(ui_font_hum);
LV_FONT_DECLARE(ui_font_sun);
LV_FONT_DECLARE(ui_font_smoke);
LV_FONT_DECLARE(ui_font_eyes);
LV_FONT_DECLARE(ui_font_back);

// UI INIT
extern void ui_init(void);
extern void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
